import { randomUUID } from 'node:crypto'
import type { Deps, DayEvent } from './deps'
import type { Reflection } from './reflection'

/**
 * ISO local day (YYYY-MM-DD) for a Date. Local calendar fields so the record
 * date, the look-back window, and the log's streak walk all agree on the
 * user's local day.
 */
function isoDay(d: Date): string {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

/**
 * Read the day's calendar entries for reflection. The conversation with Claude
 * does the reflecting — this just hands it the canvas.
 */
export async function readDay(date: string, deps: Deps): Promise<DayEvent[]> {
  return deps.diary.day(date)
}

/**
 * Apply the user-APPROVED notes (additive, into each event) plus an optional
 * day summary, and record that they reflected. Content flows through here but is
 * never stored — it goes to the user's own calendar; the log keeps behaviour only.
 */
export async function applyDayNotes(
  input: { date: string; notes: { eventId: string; note: string }[]; summary?: string },
  deps: Deps,
): Promise<Reflection> {
  for (const n of input.notes) await deps.diary.annotate(n.eventId, n.note)
  if (input.summary) await deps.diary.writeSummary(input.date, input.summary)
  const reflection: Reflection = {
    id: randomUUID(),
    date: input.date,
    kind: 'after',
    status: 'shown-up',
  }
  await deps.log.add(reflection)
  return reflection
}

/** A short clock label for an event time (e.g. "09:30"). */
function eventTime(d: Date): string {
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

/**
 * Compose and send one of the two daily emails. It lists the day and asks
 * orienting questions (generated by the LLM, grounded in the user's goals), then
 * points them to reflect with their own LLM. The reflection happens THERE, not
 * here — the email is the nudge that gets them talking to their assistant.
 */
export async function composeDayEmail(kind: 'morning' | 'evening', deps: Deps): Promise<void> {
  const now = deps.clock()
  const today = isoDay(now)
  // Day-of-week is a cheap, high-signal cue — a Sunday after church, a heavy
  // weekday, a sabbath all want different questions.
  const weekday = now.toLocaleDateString([], { weekday: 'long' })
  const events = await deps.diary.day(today)
  const preferences = await deps.grounding.get()

  // Deterministic day list — the LLM never invents events.
  const dayList = events.length
    ? events.map((e) => `• ${eventTime(e.start)} — ${e.title}`).join('\n')
    : '(nothing on your calendar today)'

  const context = [
    preferences ? `Their preferences:\n${preferences}` : 'No preferences set yet.',
    `Today is ${weekday} (${today}).`,
    `Their day:\n${dayList}`,
  ].join('\n\n')
  const questions = (await deps.reflect(kind, { notes: context })).text.trim()

  // A starter they can take to ANY assistant, with deep links for the common ones.
  const opener =
    kind === 'morning'
      ? 'I want to reflect on the day ahead and orient it toward God. Questions I am holding:'
      : 'I want to reflect on my day and notice where God was in it. Questions I am holding:'
  const starter = `${opener}\n\n${questions}`
  const claudeLink = `https://claude.ai/new?q=${encodeURIComponent(starter)}`
  const chatgptLink = `https://chatgpt.com/?q=${encodeURIComponent(starter)}`

  const when = kind === 'morning' ? 'this morning' : 'this evening'
  const body = [
    `Your day (${today}):`,
    dayList,
    '',
    'To orient it toward God:',
    questions,
    '',
    'Reflect now — talk it through with your assistant:',
    `  Claude:  ${claudeLink}`,
    `  ChatGPT: ${chatgptLink}`,
    '',
    'Or paste this into any assistant you use:',
    starter,
  ].join('\n')

  await deps.mailer(`joshua421 · ${when}`, body)
}

export { isoDay }
