import { randomUUID } from 'node:crypto'
import type { Deps, DayEvent, SourceEvent } from './deps'
import type { Note, Reflection } from './reflection'

/** What an act-flow returns: the reflection recorded + the (transient) note. */
export interface FlowResult {
  reflection: Reflection
  note: Note
}

/**
 * ISO local day (YYYY-MM-DD) for a Date. Local calendar fields so the record
 * date, the look-back window, and the log's streak walk all agree on the
 * user's local day.
 */
function isoDay(d: Date): string {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

/** BEFORE — help bring a God-honouring posture into an upcoming event. */
export async function prepareForEvent(event: SourceEvent, deps: Deps): Promise<FlowResult> {
  const note = await deps.reflect('before', { event })
  await deps.notify(note, { eventRef: event.id })
  const reflection: Reflection = {
    id: randomUUID(),
    date: isoDay(deps.clock()),
    kind: 'before',
    status: 'shown-up',
    eventRef: event.id,
  }
  await deps.log.add(reflection)
  return { reflection, note }
}

/** AFTER / end of day — reflect on the day, tying it back to God's faithfulness. */
export async function reflectOnDay(deps: Deps): Promise<FlowResult> {
  const today = isoDay(deps.clock())
  const ctx = await deps.source.contextForDay(today)
  const note = await deps.reflect('after', ctx)
  await deps.notify(note)
  const reflection: Reflection = {
    id: randomUUID(),
    date: today,
    kind: 'after',
    status: 'shown-up',
  }
  await deps.log.add(reflection)
  return { reflection, note }
}

/**
 * LOOK BACK — "look how faithful God has been." Built from the log alone
 * (dates, kinds, streak), never from the content of what was written.
 */
export async function lookBack(deps: Deps): Promise<Note> {
  const reflections = await deps.log.reflections()
  const streak = await deps.log.streak()

  const cutoff = isoDay(new Date(deps.clock().getTime() - 13 * 24 * 60 * 60 * 1000))
  const last14 = reflections.filter((r) => r.date >= cutoff).length

  const record = reflections.map((r) => `${r.date} ${r.kind}`).join(', ')
  const notes = [
    `total reflections: ${reflections.length}`,
    `reflections in the last 14 days: ${last14}`,
    `current streak: ${streak}`,
    `record: ${record}`,
  ].join('\n')

  const note = await deps.reflect('look-back', { notes })
  await deps.notify(note)
  return note
}

/**
 * Read the day's calendar entries for reflection. The conversation with Claude
 * does the reflecting — this just hands it the canvas.
 */
export async function readDay(date: string, deps: Deps): Promise<DayEvent[]> {
  return deps.diary.day(date)
}

/**
 * Apply the user-APPROVED notes (additive, into each event) plus an optional
 * day summary, and record that they reflected. Content flows through here but is
 * never stored — it goes to the user's own calendar; the log keeps behaviour only.
 */
export async function applyDayNotes(
  input: { date: string; notes: { eventId: string; note: string }[]; summary?: string },
  deps: Deps,
): Promise<Reflection> {
  for (const n of input.notes) await deps.diary.annotate(n.eventId, n.note)
  if (input.summary) await deps.diary.writeSummary(input.date, input.summary)
  const reflection: Reflection = {
    id: randomUUID(),
    date: input.date,
    kind: 'after',
    status: 'shown-up',
  }
  await deps.log.add(reflection)
  return reflection
}

/** A short clock label for an event time (e.g. "09:30"). */
function eventTime(d: Date): string {
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

/**
 * Compose and send one of the two daily emails. It lists the day and asks
 * orienting questions (generated by the LLM, grounded in the user's goals), then
 * points them to reflect with their own LLM. The reflection happens THERE, not
 * here — the email is the nudge that gets them talking to their assistant.
 */
export async function composeDayEmail(kind: 'morning' | 'evening', deps: Deps): Promise<void> {
  const today = isoDay(deps.clock())
  const events = await deps.diary.day(today)
  const goals = await deps.grounding.get()

  // Deterministic day list — the LLM never invents events.
  const dayList = events.length
    ? events.map((e) => `• ${eventTime(e.start)} — ${e.title}`).join('\n')
    : '(nothing on your calendar today)'

  const context = [
    goals ? `The person's goals:\n${goals}` : 'No goals set yet.',
    `Their day (${today}):\n${dayList}`,
  ].join('\n\n')
  const questions = (await deps.reflect(kind, { notes: context })).text.trim()

  // A starter they can take to ANY assistant, with deep links for the common ones.
  const opener =
    kind === 'morning'
      ? 'I want to reflect on the day ahead and orient it toward God. Questions I am holding:'
      : 'I want to reflect on my day and notice where God was in it. Questions I am holding:'
  const starter = `${opener}\n\n${questions}`
  const claudeLink = `https://claude.ai/new?q=${encodeURIComponent(starter)}`
  const chatgptLink = `https://chatgpt.com/?q=${encodeURIComponent(starter)}`

  const when = kind === 'morning' ? 'this morning' : 'this evening'
  const body = [
    `Your day (${today}):`,
    dayList,
    '',
    'To orient it toward God:',
    questions,
    '',
    'Reflect now — talk it through with your assistant:',
    `  Claude:  ${claudeLink}`,
    `  ChatGPT: ${chatgptLink}`,
    '',
    'Or paste this into any assistant you use:',
    starter,
  ].join('\n')

  await deps.mailer(`joshua421 · ${when}`, body)
}

export { isoDay }
